Make sure eden_dirstate.walk() returns a dict instead of a list.
Summary:
I'm surprised this didn't cause large and obvious failures sooner, but in the
special case we introduced for `hg add` in our custom `walk()` implementation,
we were returning a `list` instead of a `dict`. I suppose if the return value
were primarily used as an iterator, that would explain how we were able to sweep
this under the rug for so long.

However, today I investigated why `hg ci -i` wasn't working. In the stacktrace,
I saw this error:

```
File "/usr/lib64/python2.7/site-packages/mercurial/scmutil.py", line 711, in marktouched
  added, unknown, deleted, removed, forgotten = _interestingfiles(repo, m)
File "/usr/lib64/python2.7/site-packages/mercurial/scmutil.py", line 747, in _interestingfiles
  for abs, st in walkresults.iteritems():
AttributeError: 'list' object has no attribute 'iteritems'
```

This quickly led me to our `walk()` function. Fortunately, Mercurial's dirstate
has a clear docstring on the contract for this method:

https://phab.mercurial-scm.org/diffusion/HG/browse/default/mercurial/dirstate.py;ec306bc6915b1bcc81f0790f785065d24354d9d2$1023-1033

so the fix was pretty straightforward.

(Note: this ignores all push blocking failures!)

Reviewed By: simpkins

Differential Revision: D5698389

fbshipit-source-id: cfbef5644c26840f1536785473d5e9770aa19c72